name: Build sample Java Maven project
 
on: [push, pull_request]
 
jobs:
  # existing jobs ..
 
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    name: Build Docker Container and Deploy to Kubernetes
    steps:
    - uses: actions/checkout@v2
    - name: Download Maven build artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact.jar
        path: github-actions-java-maven/target
          
